# Generated by Django 5.2.3 on 2025-06-15 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name_plural': 'Marks'},
        ),
        migrations.AddField(
            model_name='marks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject')},
        ),
    ]
