# Generated by Django 5.2.3 on 2025-06-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_grade'),
        ('students', '0006_alter_marks_options_marks_created_at_marks_published_and_more'),
    ]

    operations = [
    ]
